inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec_rails
  
require:
  - rubocop-factory_bot

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'config/routes.rb'
    - 'bin/yarn'
    - 'bin/setup'
    - 'bin/update'
    - 'config/spring.rb'
    - 'Rakefile'
    - 'config.ru'
    - 'config/application.rb'
    - 'app/models/application_record.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/environments/*.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Naming/MemoizedInstanceVariableName:
  Enabled: false

# There are some which cause test failures. If enabled this should be run without -A and checked.
Style/RedundantInitialize:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/CaseEquality:
  Exclude:
    - 'config/initializers/02_proc.rb'

# Causes a lot of Rubocop errors
RSpecRails/InferredSpecType:
  Enabled: false
